# Generated by Django 4.0.4 on 2022-04-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
    ]
