# Generated by Django 4.0.3 on 2022-04-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0006_alter_cliente_codigo_alter_cliente_senha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
